name: Docker
run-name: Docker => ${{  github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}

on:
  push:
    tags:
      - release-v*.*.*
  pull_request:
    branches: ["main"]

jobs:
  tags: # determine image and dockerfile based on tag
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.set.outputs.dockerfile }}
      image: ${{ steps.set.outputs.image }}
      context: ${{ steps.set.outputs.context }}
    steps:
      - name: Set image and dockerfile
        id: set
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          IMAGE=""
          DOCKERFILE=""
          CONTEXT="."

          case "$TAG" in
            release-v*.*.*)
              IMAGE="release-cd"
              DOCKERFILE="app/release/docker/release-cd.Dockerfile"
              ;;
          esac

          echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

  build:
    uses: infitx-org/actions/.github/workflows/docker.yaml@main
    needs: tags
    if: ${{ needs.tags.outputs.image != '' || github.event_name == 'pull_request' }}
    with:
      dockerfile: ${{ needs.tags.outputs.dockerfile }}
      image: ${{ needs.tags.outputs.image }}
      context: ${{ needs.tags.outputs.context }}
      license-scan: false
      downstream: https://api.github.com/repos/infitx-org/profile-cd/actions/workflows/docker-image.yaml/dispatches
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      TRIGGER_DOWNSTREAM: ${{ secrets.TRIGGER_DOWNSTREAM }}
