name: Docker
run-name: Docker => ${{  github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}

on:
  push:
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: docker/release-cd.Dockerfile
            image: release-cd
            context: .
    uses: infitx-org/actions/.github/workflows/docker.yaml@main
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image: ${{ matrix.image }}
      context: ${{ matrix.context }}
      owner: ${{ github.repository_owner }}
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      TRIGGER_DOWNSTREAM: ${{ secrets.TRIGGER_DOWNSTREAM }}
